Repository CHUPITO-Org/IaC-Chupito-Azure, pull requests merged in 2023-11, with the labels that each got.

#4 feat: Add docs: diagram, costs
  docs/Az-Cost-Estimated.xlsx
  docs/azure_architecture.drawio
  docs/azure_architecture.png
  docs/azure_architecture_costs.md
  main.tf
Labels: documentation

#6 feat: Adding rg, vnet, container registry
  .trunk/trunk.yaml
  README.md
  main.tf
  modules/network/main.tf
  modules/network/variables.tf
  providers.tf
  variables.tf
Labels: enhancement

#7 Fix: remove tflint & remove providers from module
  .pre-commit-config.yaml
  README.md
  modules/network/main.tf
  variables.tf
Labels: bug

#10 Feat: Add pull request template & add acr module
  .github/pull_request_template.md
  README.md
  main.tf
  modules/container-registry/main.tf
  modules/container-registry/variables.tf
  variables.tf
Labels: documentation, enhancement

#11 feat(modules): add container-instance module
  README.md
  main.tf
  modules/container-instance/main.tf
  modules/container-instance/variables.tf
  modules/container-registry/main.tf
  modules/container-registry/variables.tf
  modules/network/main.tf
  modules/network/variables.tf
  variables.tf
Labels: enhancement

#12 bugfix(pipeline): Add commit to main to update CHANGELOG
  .github/workflows/merge-master.yml
Labels: enhancement

#16 feat(container): add database container with intialize values and volume
  main.tf
  modules/container-instance/main.tf
  modules/container-instance/variables.tf
  modules/storage/main.tf
  variables.tf
Labels: enhancement
